name: Release Charts

on:
  push:
    branches:
      - trunk
      - feature-signed-charts

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-releaser
        uses: shift/chart-releaser-signed-action@v1.4.1-alpha1
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PGP_SIGNING_KEY: "${{ secrets.GPG_SIGNING_KEY }}"
          PGP_KEY_NAME: "${{ secrets.GPG_KEY_NAME }}"
